//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class tCustomer
{
    public long CustomerId { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public long CustomerCode { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public string Address { get; set; }
    public Nullable<System.DateTime> InsertDate { get; set; }
    public Nullable<System.DateTime> ModifyDate { get; set; }
}

public partial class tProduct
{
    public long ProductId { get; set; }
    public long ProductCode { get; set; }
    public string ProductTitle { get; set; }
    public int ProductLevel { get; set; }
    public int LevelType { get; set; }
}

public partial class tTracking
{
    public long TrackId { get; set; }
    public long CustomerId { get; set; }
    public int LessionId { get; set; }
    public int LessionStatus { get; set; }
    public System.DateTime InsertDate { get; set; }
    public Nullable<System.DateTime> ActiveDate { get; set; }
}
