//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _365Days.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class tProduct
    {
        public long ProductId { get; set; }
        public long ProductCode { get; set; }
        public string ProductTitle { get; set; }
        public int ProductLevel { get; set; }
        public int LevelType { get; set; }
    }
}
