//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _365Days.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTracking
    {
        public long TrackId { get; set; }
        public long CustomerId { get; set; }
        public int LessionId { get; set; }
        public int LessionStatus { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
    }
}
