

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class tb_About
{

    public long AboutArticleID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Contents { get; set; }

    public string Image { get; set; }

    public string Status { get; set; }

    public string Kind { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<long> UpdateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UrlFriendLy { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDescription { get; set; }

    public string MetaKeyWord { get; set; }

    public string MetaImage { get; set; }

}


public partial class tb_Access
{

    public long LocalAccountID { get; set; }

    public Nullable<int> AccessCount { get; set; }

}


public partial class tb_CategoryMain
{

    public long MainCateID { get; set; }

    public string MainCateName { get; set; }

    public Nullable<int> Sort { get; set; }

    public string MainCateDesc { get; set; }

    public System.DateTime CreateDate { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public string MainCateIcon { get; set; }

    public string MainCateBanner { get; set; }

}


public partial class tb_CategorySub1
{

    public long SubCate1ID { get; set; }

    public string SubCate1Name { get; set; }

    public Nullable<long> MainCateID { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public string SubCate1Desc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<byte> Sort { get; set; }

}


public partial class tb_CategorySub2
{

    public long SubCate2ID { get; set; }

    public string SubCate2Name { get; set; }

    public Nullable<long> SubCate1ID { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public string SubCate2Desc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<int> Sort { get; set; }

}


public partial class tb_CategorySub3
{

    public long SubCate3ID { get; set; }

    public string SubCate3Name { get; set; }

    public Nullable<long> SubCate2ID { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public string SubCate2Desc { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<byte> Sort { get; set; }

}


public partial class tb_ContactMessage
{

    public int MessageID { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string PhoneNumber { get; set; }

    public string EmailAddress { get; set; }

    public string MessageTitle { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string IsRead { get; set; }

    public string MessageContent { get; set; }

}


public partial class tb_ContactUs
{

    public long ContactID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string CellPhone { get; set; }

    public string HomePhone { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<bool> Finished { get; set; }

    public Nullable<bool> ReadNew { get; set; }

    public string MessageContent { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ReadDate { get; set; }

    public Nullable<System.DateTime> FinishDate { get; set; }

    public Nullable<byte> Status { get; set; }

}


public partial class tb_Counteronline
{

    public long CounterID { get; set; }

    public int TotalUserOnline { get; set; }

    public Nullable<int> TotalOnline { get; set; }

    public Nullable<int> TotalClick { get; set; }

    public Nullable<byte> Flag { get; set; }

}


public partial class tb_Country
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Country()
    {

        this.tb_Province = new HashSet<tb_Province>();

    }


    public int Id { get; set; }

    public string CountryCode { get; set; }

    public string CommonName { get; set; }

    public string FormalName { get; set; }

    public string CountryType { get; set; }

    public string CountrySubType { get; set; }

    public string Sovereignty { get; set; }

    public string Capital { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }

    public string TelephoneCode { get; set; }

    public string CountryCode3 { get; set; }

    public string CountryNumber { get; set; }

    public string InternetCountryCode { get; set; }

    public Nullable<int> SortOrder { get; set; }

    public Nullable<bool> IsPublished { get; set; }

    public string Flags { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Province> tb_Province { get; set; }

}


public partial class tb_Customer
{

    public long CustomerID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public Nullable<bool> Gender { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public Nullable<byte> Status { get; set; }

    public string Avatar { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CustomerNo { get; set; }

    public string Description { get; set; }

    public Nullable<int> CustomerGroup { get; set; }

}


public partial class tb_DeliverySelection
{

    public long DeliverySelectionID { get; set; }

    public string DeliveryName { get; set; }

    public string DeliveryDescription { get; set; }

    public Nullable<int> SortBy { get; set; }

    public Nullable<double> DeliveryCost { get; set; }

}


public partial class tb_District
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_District()
    {

        this.tb_Ward = new HashSet<tb_Ward>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string LatiLongTude { get; set; }

    public int ProvinceId { get; set; }

    public Nullable<int> SortOrder { get; set; }

    public Nullable<bool> IsPublished { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tb_Province tb_Province { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_Ward> tb_Ward { get; set; }

}


public partial class tb_DocumentSelection
{

    public long DocumentSelectionID { get; set; }

    public string DocumentName { get; set; }

    public string DocumentDescription { get; set; }

}


public partial class tb_GetLinkImage
{

    public int imgID { get; set; }

    public string imgPath { get; set; }

    public Nullable<System.DateTime> imgUpload { get; set; }

}


public partial class tb_GroupCustomer
{

    public int GroupCusID { get; set; }

    public string GroupCusCode { get; set; }

    public string GroupCusName { get; set; }

    public string GroupCusDesc { get; set; }

    public Nullable<double> GroupCusValue { get; set; }

    public Nullable<bool> IsDisplay { get; set; }

    public Nullable<bool> IsDeleted { get; set; }

    public Nullable<System.DateTime> GroupCusCreate { get; set; }

}


public partial class tb_HomeBanner
{

    public long HomeBannerID { get; set; }

    public string BannerDescription { get; set; }

    public string BannerGroup { get; set; }

    public string BannerLandingpage { get; set; }

    public string BannerPath { get; set; }

    public Nullable<System.DateTime> BannerUpload { get; set; }

}


public partial class tb_HomeMainBanner
{

    public long HomeMainBannerID { get; set; }

    public string BannerPath { get; set; }

    public string BannerDescription { get; set; }

    public string BannerLandingpage { get; set; }

    public Nullable<System.DateTime> BannerUpload { get; set; }

    public string BannerHeader1 { get; set; }

    public string BannerHeader2 { get; set; }

    public Nullable<int> SortArr { get; set; }

}


public partial class tb_HomeProductGroup
{

    public long ProductGroupID { get; set; }

    public string ProductGroupName { get; set; }

    public Nullable<byte> Sort { get; set; }

    public Nullable<bool> Status { get; set; }

}


public partial class tb_LocalAccount
{

    public long LocalAccountID { get; set; }

    public string AccountCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public Nullable<bool> Gender { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<long> PermissionID { get; set; }

    public string Avatar { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

}


public partial class tb_Order
{

    public long OrderID { get; set; }

    public Nullable<long> CustomerID { get; set; }

    public string OrderCode { get; set; }

    public Nullable<byte> OrderType { get; set; }

    public Nullable<double> DiscountAmount { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> PickupTime { get; set; }

    public Nullable<System.DateTime> ReturnTime { get; set; }

    public Nullable<int> Quantity { get; set; }

    public Nullable<long> ServiceSelectionID { get; set; }

    public Nullable<long> DeliverySelectionID { get; set; }

    public Nullable<long> DocumentSelectionID { get; set; }

    public Nullable<double> TotalDepositAmount { get; set; }

    public Nullable<double> TotalOrderValue { get; set; }

    public Nullable<byte> OrderStatus { get; set; }

    public Nullable<long> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedDate { get; set; }

    public Nullable<bool> UpdatingStatus { get; set; }

}


public partial class tb_OrderAccessorySelection
{

    public long AccessorySelectionID { get; set; }

    public Nullable<long> OrderID { get; set; }

    public Nullable<long> ProductID { get; set; }

    public Nullable<int> Quantity { get; set; }

}


public partial class tb_OrderTrackingUpdate
{

    public long OrderTrackingUpdateID { get; set; }

    public long OrderID { get; set; }

    public Nullable<long> LocalAccount { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> ReturnDate { get; set; }

}


public partial class tb_Permission
{

    public long PermissionID { get; set; }

    public string PermissionName { get; set; }

    public string PermissionDescription { get; set; }

}


public partial class tb_Product
{

    public long ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string ProductAvatar { get; set; }

    public string ProductCity { get; set; }

    public string ProductDistrict { get; set; }

    public string ProductWard { get; set; }

    public string ShortDescription { get; set; }

    public string FullDescription { get; set; }

    public string ProductSpecification { get; set; }

    public string ProductInstruction { get; set; }

    public Nullable<int> StatusPercentage { get; set; }

    public Nullable<byte> StatusAvailability { get; set; }

    public Nullable<double> PricePerBlock { get; set; }

    public Nullable<double> PricePerDay { get; set; }

    public long ProductMainCate { get; set; }

    public long ProductSubCate1 { get; set; }

    public long ProductSubCate2 { get; set; }

    public long ProductSubCate3 { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<double> ProductValue { get; set; }

    public string ListBy1 { get; set; }

    public string ListBy2 { get; set; }

    public string ListBy3 { get; set; }

    public string ListBy4 { get; set; }

    public string ListBy5 { get; set; }

    public string ListBy6 { get; set; }

    public string ListBy7 { get; set; }

    public string YoutubeLink { get; set; }

    public Nullable<int> SetPriceBlock { get; set; }

    public Nullable<int> SetPriceDay { get; set; }

}


public partial class tb_ProductAccessorySelection
{

    public long ProductAccessorySelectionID { get; set; }

    public long ProductID { get; set; }

    public string ProductName { get; set; }

    public string ProductCode { get; set; }

    public Nullable<double> PricePerBlock { get; set; }

    public Nullable<double> PricePerDay { get; set; }

    public Nullable<double> ProductValue { get; set; }

}


public partial class tb_ProductAccompany
{

    public long ProductAccompany { get; set; }

    public Nullable<long> ProductID { get; set; }

    public string ProductName { get; set; }

    public string ProductCode { get; set; }

    public string productAccAvatar { get; set; }

}


public partial class tb_ProductGallery
{

    public long ImageID { get; set; }

    public long ProductID { get; set; }

    public string ImagePath { get; set; }

}


public partial class tb_ProductHomeProductGroup
{

    public long ProductHomeProductGroupID { get; set; }

    public long ProductID { get; set; }

    public long ProductGroupID { get; set; }

}


public partial class tb_Promotion
{

    public long PromotionID { get; set; }

    public Nullable<double> DiscountByPercentage { get; set; }

    public Nullable<double> DiscountByPrice { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public Nullable<byte> Status { get; set; }

    public Nullable<byte> KindPromotion { get; set; }

}


public partial class tb_Province
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tb_Province()
    {

        this.tb_District = new HashSet<tb_District>();

    }


    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public Nullable<int> TelephoneCode { get; set; }

    public string ZipCode { get; set; }

    public int CountryId { get; set; }

    public string CountryCode { get; set; }

    public Nullable<int> SortOrder { get; set; }

    public Nullable<bool> IsPublished { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tb_Country tb_Country { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tb_District> tb_District { get; set; }

}


public partial class tb_ServiceSelection
{

    public long ServiceSelectionID { get; set; }

    public string ServiceName { get; set; }

    public string ServiceDescription { get; set; }

    public Nullable<double> ServiceCost { get; set; }

    public Nullable<int> SortBy { get; set; }

}


public partial class tb_SiteMap
{

    public long SiteMapID { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Contents { get; set; }

    public string Image { get; set; }

    public Nullable<byte> Status { get; set; }

    public string Kind { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public Nullable<long> UpdateBy { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }

    public string UrlFriendLy { get; set; }

    public string MetaTitle { get; set; }

    public string MetaDescription { get; set; }

    public string MetaKeyWord { get; set; }

    public string MetaImage { get; set; }

}


public partial class tb_Ward
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string LatiLongTude { get; set; }

    public int DistrictID { get; set; }

    public int SortOrder { get; set; }

    public Nullable<bool> IsPublished { get; set; }

    public Nullable<bool> IsDeleted { get; set; }



    public virtual tb_District tb_District { get; set; }

}


public partial class tb_WishList
{

    public long WishListID { get; set; }

    public long ProductID { get; set; }

    public long CustomerID { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

}

